version: '3.8'

services:
  gps-scraper:
    build: .
    container_name: gps-scraper
    restart: unless-stopped
    environment:
      - USERNAME=LuisDiaZ
      - PASSWORD=Supervision/25
      - TZ=America/Tijuana
      - MYSQL_HOST=195.35.61.124
      - MYSQL_DATABASE=u821270692_techlogicredyb
      - MYSQL_USER=u821270692_redyb
      - MYSQL_PASSWORD=Perrosucio18
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./resultados:/app/resultados
      - ./logs:/app/logs
