version: '3.8'

services:
  gps-scraper:
    build: .
    container_name: gps-scraper
    restart: unless-stopped
    environment:
      - USERNAME=LuisDiaZ
      - PASSWORD=Supervision/25
      - TZ=America/Tijuana
    volumes:
      - ./resultados:/app/resultados
      - ./logs:/app/logs
