version: '3.8'

services:
  gps-scraper:
    build: .
    container_name: gps-scraper
    restart: unless-stopped
    environment:
      - USERNAME=LuisDiaZ
      - PASSWORD=Supervision/25
      - TZ=America/Tijuana
      - SPREADSHEET_ID=1OU-GcQP030R-
      - SHEET_NAME=Hoja 1
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./resultados:/app/resultados
      - ./logs:/app/logs
